# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceSchedule',
            new_name='DeviceEvent',
        ),
        migrations.RenameField(
            model_name='deviceevent',
            old_name='change_to',
            new_name='activation',
        ),
    ]
