# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_auto_20170201_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='activation_frequecy',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_activation',
            field=models.DateTimeField(null=True),
        ),
    ]
