# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0005_device_activation_dose'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='activation_frequecy',
            new_name='activation_frequency',
        ),
    ]
