# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('subtype', models.CharField(max_length=10)),
                ('gpio_pin', models.IntegerField()),
                ('potency', models.DecimalField(decimal_places=2, max_digits=8)),
                ('potency_unit', models.CharField(max_length=32)),
                ('activation_mode', models.CharField(max_length=32)),
            ],
        ),
    ]
