# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_dt', models.DateTimeField()),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('log_dt',),
            },
        ),
        migrations.CreateModel(
            name='DeviceSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_dt', models.DateTimeField()),
                ('change_to', models.IntegerField()),
            ],
            options={
                'ordering': ('event_dt',),
            },
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='deviceschedule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.Device'),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Device.Device'),
        ),
    ]
