# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0003_auto_20170201_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
